rotterdam_port/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('ship.urls')),
    url(r'^admin/', admin.site.urls),
]

ship/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^dock/(?P<id>[0-9]+)/$', dock_detail, name='dock_detail'),
]

dock/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ship.models import Ship


JOB_STATUS = (
    ('1', _("Enqueue")),
    ('2', _("Active Job")),
    ('3', _("Job done | Dequeue")),
)


class Dock(models.Model):
    name = models.CharField(
        _('Dock unique identifier'),
        max_length=150,
        unique=True,
    )

    class Meta:
        verbose_name = _('Dock')
        verbose_name_plural = _('Docks')

    def __unicode__(self):
        return self.name

    def get_active_job(self):
        try:
            return Job.objects.get(dock=self, job_status=2)
        except Job.DoesNotExist:
            return None


class Job(models.Model):
    dock = models.ForeignKey(
        Dock
    )
    ship = models.ForeignKey(
        Ship
    )
    job_status = models.CharField(
        choices=JOB_STATUS,
        max_length=1
    )
    start_time = models.DateTimeField(
        _("Job start date and time")
    )
    end_time = models.DateTimeField(
        _("Job end date and time"),
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _('Jobs')
        verbose_name_plural = _('Jobs')
        unique_together = (("dock", "ship"),)

    def __unicode__(self):
        return '%s %s'% (self.dock.name, self.ship.name)

    def save(self, *args, **kwargs):
        if not self.id and not Job.objects.\
                filter(dock=self.dock, job_status='2').exists():
            super(Job, self).save(*args, **kwargs)
        return

employee/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

from dock.models import Dock


class Employee(AbstractUser):
    address = models.CharField(
        _('Employee address'),
        max_length=90,
    )
    bank_account = models.CharField(
        _('Employee bank account number'),
        max_length=90,
    )
    supervisor = models.ForeignKey(
        "self",
        null=True,
        blank=True,
    )
    dock = models.ForeignKey(
        Dock,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')

    def __unicode__(self):
        if self.first_name or self.last_name:
            return '%s %s' % (self.first_name, self.last_name)
        else:
            return self.username

ship/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _

HAZARD_CHOICES = (
    ('0', _("No hazard")),
    ('1', _("Fire hazard")),
    ('2', _("Chemical hazard")),
)


class Ship(models.Model):
    name = models.CharField(
        _('Ship unique identifier'),
        max_length=150,
        unique=True,
    )
    arrival_time = models.DateTimeField(
        _('Ship arrival time'),
    )
    description = models.TextField(
        _("Historic overview"),
    )

    class Meta:
        verbose_name = _('Ship')
        verbose_name_plural = _('Ships')

    def __unicode__(self):
        return self.name

    def get_hazard_status(self):
        if Container.objects.filter(ship=self, hazard__in=['1', '2']).exists():
            return "Hazardies"
        return "No hazard"


class Container(models.Model):
    name = models.CharField(
        _('Container unique identifier'),
        max_length=150,
        unique=True,
    )
    ship = models.ForeignKey(
        Ship,
    )
    hazard = models.CharField(
        max_length=1,
        choices=HAZARD_CHOICES
    )

    class Meta:
        verbose_name = _('Container')
        verbose_name_plural = _('Containers')

    def __unicode__(self):
        return self.name

employee/forms.py
from django.contrib.auth.forms import UserChangeForm
from .models import Employee


class EmployeeAdminForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Employee

ship/forms.py
from django import forms

# Create your models here.

dock/views.py
from django.shortcuts import render

# Create your views here.

employee/views.py
from django.shortcuts import render

# Create your views here.

ship/views.py
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse

from dock.models import Dock, Job
from ship.models import Ship, Container
from employee.models import Employee


def home(request):
    result = []

    for item in Dock.objects.all():
        try:
            ship = Job.objects.filter(dock=item, job_status='2').order_by('-id')[0].ship
        except IndexError:
            ship = None

        result.append(
            {
                'dock': item,
                'ship': ship
            }
        )

    context = {
        'result': result
    }
    return render(request, 'index.html', context)


def dock_detail(request, id):
    try:
        dock = Dock.objects.get(id=id)
    except Dock.DoesNotExist:
        messages.error(request, 'Dock does not exist.')
        return HttpResponseRedirect(reverse('home'))

    employee_list = Employee.objects.filter(dock=dock)

    try:
        ship = Job.objects.filter(dock=dock, job_status='2').order_by('-id')[0].ship
    except IndexError:
        ship = None

    contianer_list = []
    if ship:
        contianer_list = Container.objects.filter(ship=ship)

    context = {
        'dock': dock,
        'ship': ship,
        'contianer_list': contianer_list,
        'employee_list': employee_list,
        'total_employees': employee_list.count(),
        'total_ships_service': Job.objects.filter(dock=dock, job_status='3').count(),
        'total_enqueue_ships': Job.objects.filter(dock=dock, job_status='1').count(),
    }
    return render(request, 'detail.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Candidate Assignment – Implementation</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Candidate Assignment – Implementation</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse pull-right">
          <ul class="nav navbar-nav">
            <li><a href="/admin/">Admin</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container">
    {% block content %}
    {% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
</body></html>

templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="caption">
        <h3>
            <small>Dock Name</small>
            {{ dock }}
        </h3>
        <p>
            <strong>Total Employees on the dock:</strong> {{ total_employees }}<br/>
            <strong> Total number of ships serviced on this dock:</strong> {{ total_ships_service }}<br/>
            <strong> Total enqueue ships on this dock:</strong> {{ total_enqueue_ships }}
        </p>
    </div>

    <div class="caption">
        <h3>
            <small>Current Parked Ship</small>
            {{ ship }}
        </h3>
        <p>
            {{ ship.description }}
        </p>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">Containers on the ship</div>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Container Name</th>
                    <th>Hazard</th>
                </tr>
            </thead>
            <tbody>
            {% for item in contianer_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.name }}</td>
                    <td>{{ item.get_hazard_display }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="panel panel-default">
        <div class="panel-heading">Employees working on the Ship</div>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>last Name</th>
                    <th>Address</th>
                    <th>Bank account</th>
                    <th>Supervisor</th>
                    <th>Dock</th>
                </tr>
            </thead>
            <tbody>
            {% for item in employee_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.first_name }}</td>
                    <td>{{ item.last_name }}</td>
                    <td>{{ item.address }}</td>
                    <td>{{ item.bank_account }}</td>
                    <td>{{ item.supervisor }}</td>
                    <td>{{ item.dock }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="starter-template">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Dock Name</th>
                    <th>Ship Name</th>
                    <th>Hazard</th>
                </tr>
            </thead>
            <tbody>
            {% for item in result %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        <a href="{% url 'dock_detail' id=item.dock.id %}">
                            {{ item.dock }}
                        </a>
                    </td>
                    <td>
                        {% if item.ship %}
                            {{ item.ship }}
                        {% else %}
                            No ship Assign
                        {%  endif %}
                    </td>
                    <td>
                        {% if item.ship %}
                            {{ item.ship.get_hazard_status }}
                        {% else %}
                            No ship Assign
                        {%  endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}